version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - '8077:80'
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '5506:3306' 
    restart: unless-stopped